from django.test import TestCase
from .models import StateCensusTract, censustract_mapping


class StateCensusTractModelTest(TestCase):

    def test_census_tract_mapping(self):
        """ This mapping is generated by ogrinspect. This test ensures we
        don't inadvertently change it. Otherwise, data loading won't work. """

        for key, value in censustract_mapping.items():
            if key == 'geom':
                self.assertEqual(value, 'MULTIPOLYGON')
            else:
                self.assertEqual(key.upper(), value)
